---
- name: VPN
  hosts: all
  become: yes

  tasks:
  - name: install epel-release on CentOS
    ansible.builtin.yum:
      name: epel-release
      state: present

  - name: install softs on CentOS
    ansible.builtin.yum:
      name:
        - nano
        - openvpn
        - easy-rsa
      state: present

  - name: Disable SELinux
    selinux:
      state: disabled

  - name: copy server.conf client
    template:
      src: server_2.conf
      dest: /etc/openvpn/server.conf

  - name: Start script
    script: /home/nakhorenko/Linux-2022-12/otus-vpn/vpn.sh

  - name: copy ca.crt to host
    fetch:
      src: /etc/openvpn/pki/ca.crt
      dest: /home/nakhorenko/Linux-2022-12/otus-vpn/ca.crt

  - name: copy client.crt to host
    fetch:
      src: /etc/openvpn/pki/issued/client.crt
      dest: /home/nakhorenko/Linux-2022-12/otus-vpn/client.crt

  - name: copy client.key to host
    fetch:
      src: /etc/openvpn/pki/private/client.key
      dest: /home/nakhorenko/Linux-2022-12/otus-vpn/client.key

  - name: Creates openvpn service
    template:
      src: openvpn@.service
      dest: /etc/systemd/system/openvpn@.service

  - name: start openvpn@server
    service:
      name: openvpn@server
      state: started
      enabled: true
